client_config_backend: file
client_config:
    client_id: CLIENT ID HERE
    client_secret: CLIENT SECRET HERE

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install
    - https://www.googleapis.com/auth/drive.metadata